#### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [27]:
def divbyzero():
    try:
        x = 5/0
    except ZeroDivisionError as y:
        print('Exception handled successfully: ' , y)

In [28]:
divbyzero()

Exception handled successfully:  division by zero


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [19]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

def inputs(subjects,verbs,objects):
    for s in subjects:
        for v in verbs:
            for o in objects:
                output=s+" "+v+" "+o
                yield output

In [25]:
out=inputs(subjects,verbs,objects)
for element in out :
    print(element)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


#### TASK 2
#### 1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [24]:
## User defined Python function
def a_vander(a_list, is_incr):
    n = len(a_list)
    out=[]
    for element in a_list:
        temp=[]
        if(is_incr):
            for i in range(n):
                temp.append(element**i)
            out.append(temp)
        else:
            for i in range(n-1,-1,-1):
                temp.append(element**i)
            out.append(temp)
    return out

In [22]:
import numpy as np
v=[1, 2, 3, 4, 5]

myarray_incr = np.asarray(a_vander(v, True))
myarray_decr = np.asarray(a_vander(v, True))

print('When Increasing is True: \n', myarray_incr)
print('When Increasing is False: \n', myarray_decr)

When Increasing is True: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
When Increasing is False: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [23]:
## Using the NumPy function
import numpy as np
x = np.array([1, 2, 3, 4])
myarray_incr_n = np.vander(x, increasing=True)
myarray_decr_n = np.vander(x, increasing=False)

print('When Increasing is True: \n', myarray_incr_n)
print('When Increasing is False: \n', myarray_decr_n)

When Increasing is True: 
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
When Increasing is False: 
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
